export const studentsData = {
  Ten: [
    {
      id: 1,
      name: "Kousik",
      roll: "",
      class_name: "দশম",
      imgLink: "https://i.ibb.co/tD1gX3b/kousik.png",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন) ",
    },

    {
      id: 2,
      name: "Moursalin",
      roll: "",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/jPPGcs4C/mursalin.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন) ",
    },
    {
      id: 3,
      name: "Shimul",
      roll: "",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 4,
      name: "Mottalib",
      roll: "",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/ynXnSZN/mottalib.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 5,
      name: "Soyaib",
      roll: "",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/WN4SLp4j/souib.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 6,
      name: "Murad",
      roll: "",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 7,
      name: "Hridoy",
      roll: "",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/nqYH65R5/ridoy.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "ক্রোড় গাছা উচ্চ বিদ্যালয়। ",
    },
    {
      id: 8,
      name: "Imran",
      roll: "",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2026-April",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 9,
      name: "Abdur Rahman",
      roll: "https://i.ibb.co.com/fYmGBCdD/ab-Rahman10.jpg",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2026-April",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 10,
      name: "Tamim",
      roll: "",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/fMQcqkQ/tamim2.png",
      joinYear: "2024-অষ্টম",
      subject: "Physics,Math",
      institutionName: "পলিটেকনিক স্কুল & কলেজ। ",
    },
  ],
  Nine: [
    {
      id: 1,
      name: "Jahid",
      roll: "",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/hFDLdbwc/jahid-Hasan-At9.jpg",
      joinYear: "২০২৬-ফেব্রুয়ারী",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },

    {
      id: 2,
      name: "Noyon Kumar",
      roll: "",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/XkMdGnQM/noyon-Kumar.jpg",
      joinYear: "২০২৬-ফেব্রুয়ারী",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 3,
      name: "Abdul Ahad",
      roll: "",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/Y4sYqgt6/ab-ahad.jpg",
      joinYear: "২০২৬-মে",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 4,
      name: "Monowar",
      roll: "",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/27Sd51WF/monowar.jpg",
      joinYear: "২০২৬-ফেব্রুয়ারী",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 5,
      name: "Tasin [Lamiya]",
      roll: "",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৫-এপ্রিল- অষ্টম শ্রেণি",
      subject: "গণিত, বিজ্ঞান",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 6,
      name: "Bulbul",
      roll: "",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-মে",
      subject: "গণিত ও বিজ্ঞান ।",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
  ],
  Eight: [
    {
      id: 1,
      name: "Md Ibrahim",
      roll: "9",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/xxW1txy/ibrahim-8-2.jpg",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 2,
      name: "Rifa",
      roll: "6",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/gZd8Vg9H/rifa.jpg",
      joinYear: "2026 -শ্রেনি-৮ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 3,
      name: "Sagorika",
      roll: "3",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/v4sYNf6x/sagorika.jpg",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 4,
      name: "Bonna",
      roll: "01",
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 5,
      name: "Mim",
      roll: "",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/svFGRBNc/mim.jpg",
      joinYear: "2026 -শ্রেনি-৮ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 6,
      name: "Likhon",
      roll: "",
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2026 -শ্রেনি-৮ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 7,
      name: "Rifat",
      roll: "",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/DD0jfXYK/rifat.jpg",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
  ],
};




export const PreviousStudentsData = {
  ssc25: [
    {
      id: 1,
      name: "Soikot",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/6c7mnWYv/soikot-26.jpg",
      joinYear: "2025",
      subject: "Physics and Chemistry",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 2,
      name: "Alif",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/7sgpnpG/alif.jpg",
      joinYear: "2025",
      subject: "Physics and Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 3,
      name: "Mehedi",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/rfXKx9xx/mehedi-26.jpg",
      joinYear: "2025",
      subject: "Physics and Chemistry",
      institutionName: "মেহেদীবাগ উচ্চ বিদ্যালয়।",
    },
    // { id: 4, name: "Shihab", batch:"SSC-2026 [২০২৫-২০২৬]",imgLink: "" ,joinYear:'',subject:"Physics and Chemistry",institutionName:"সাকসেস মডেল স্কুল (পুরাতন)"},
    {
      id: 5,
      name: "Maruf",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/1YtMMyvW/maruf-26.jpg",
      joinYear: "",
      subject: "Physics and Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    // { id: 6, name: "Riad", batch:"SSC-2026 [২০২৫-২০২৬]",imgLink: "" ,joinYear:'',subject:"Physics and Chemistry",institutionName:"সাকসেস মডেল স্কুল (পুরাতন)"},
    {
      id: 7,
      name: "Mahin",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/39CV0SLt/mahin-26.jpg",
      joinYear: "",
      subject: "Physics and Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },

    {
      id: 2,
      name: "Lamiya",
      batch: "নবম [২০২৫]",
      imgLink: "https://i.ibb.co.com/WGXGHLQ/lamiya-2.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "নুরুল হক স্কুল এন্ড কলেজ।",
    },
    {
      id: 3,
      name: "Rukaiya",
      batch: " নবম [২০২৫]",
      imgLink: "https://i.ibb.co/syMd0zG/rukaiya.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 7,
      name: "Munna",
      batch: "নবম [২০২৫]",
      imgLink: "https://i.ibb.co.com/ymj9sGtM/munna-nine.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
     {
      id: 8,
      name: "Miraz",
      batch: "অষ্টম [২০২৪]",
      imgLink: "https://i.ibb.co.com/nCVYVGz/miraz.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "আলোর মেলা শিশু নিকেতন।",
    },
    {
      id: 5,
      name: "Mohon",
      batch: "অষ্টম [২০২৪] ",
      imgLink: "https://i.ibb.co.com/9vB0Xqr/mohon2.png",
      joinYear: "2023",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },


    // ///////
    {
      id: 1,
      name: "Sathi",
      batch: "দশম [২০২৬]",
      imgLink: "https://i.ibb.co/ng54MVX/sathi.jpg",
      joinYear: "",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 3,
      name: "Sadiya",
      batch: "দশম [২০২৬]",
      imgLink: "https://i.ibb.co.com/Cv0kzMd/Capture.png",
      joinYear: "",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },





     {
      id: 1,
      name: "Luba",
      batch: "HSC ICT [2024]",
      imgLink: "https://i.ibb.co.com/ZzHXCY0/luba.jpg",
      joinYear: "2024",
      subject: "ICT",
      institutionName: "Nakai hat collage",
    },
     {
      id: 1,
      name: "Shithi",
      batch: "HSC ICT [2024]",
      imgLink: "https://i.ibb.co.com/ChN22g9/shithi-2.png",
      joinYear: "2024",
      subject: "ICT",
      institutionName: "Nakai hat collage",
    },

    {
      id: 3,
      name: "Borhan",
      batch: "HSC ICT [2024]",
      imgLink: "https://i.ibb.co.com/KDhg3v7/borhan-2.png",
      joinYear: "",
      subject: "",
      institutionName: "SKS School and Collage",
    },
  ],
  Eight: [
    // { id: 4, name: "Bayezid", batch:"অষ্টম [২০২৬]",imgLink: "" ,joinYear:'',subject:"",institutionName:"নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।"},
    // { id: 1, name: "Asha Moni", batch:"অষ্টম [২০২৫]",imgLink: " " ,joinYear:'',subject:"",institutionName:""}
  ],

  // Eight: [],
  Nine: [
   

    // { id: 9, name: "Ela Moni", batch:" [২০২৫]",imgLink: "" ,joinYear:'',subject:"",institutionName:"নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।"},
    // {
    //   id: 4,
    //   name: "Toufik",
    //   batch: " [২০২৫]",
    //   imgLink: " ",
    //   joinYear: "",
    //   subject: "",
    //   institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    // },
    
  ],
  // Eight: [],
  Ten: [
    
  ],
  // Eight: [],
  HSC: [
   
  ],
};
