export const studentsData = {
  Ten: [
    {
      id: 1,
      name: "Kousik",
      batchTime: "7 am to 8 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co/tD1gX3b/kousik.png",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন) ",
    },

    {
      id: 2,
      name: "Moursalin",
      batchTime: "7 am to 8 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/jPPGcs4C/mursalin.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন) ",
    },
    {
      id: 3,
      name: "Shimul",
      batchTime: "7 am to 8 am",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 4,
      name: "Mottalib",
      batchTime: "7 am to 8 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/ynXnSZN/mottalib.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 5,
      name: "Soyaib",
      batchTime: "7 am to 8 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/WN4SLp4j/souib.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 6,
      name: "Murad",
      batchTime: "7 am to 8 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/rR66x3gH/murad9.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 7,
      name: "Hridoy",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/nqYH65R5/ridoy.jpg",
      joinYear: "2024-৮ম শ্রেণি",
      subject: "Physics,Chemistry",
      institutionName: "ক্রোড় গাছা উচ্চ বিদ্যালয়। ",
    },
    {
      id: 8,
      name: "Imran",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/LdVgrbhS/imran-10.jpg",
      joinYear: "2026-April",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 9,
      name: "Abdur Rohman",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/Xkz5KKHL/Rohman10.jpg",
      joinYear: "2026-April",
      subject: "Physics,Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 10,
      name: "Tamim",
      batchTime: "7 am to 8 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/fMQcqkQ/tamim2.png",
      joinYear: "2024-অষ্টম",
      subject: "Physics,Math",
      institutionName: "পলিটেকনিক স্কুল & কলেজ। ",
    },
    {
      id: 11,
      name: "Riyad",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "https://i.ibb.co.com/x8tzwTnX/riyad10.jpg",
      joinYear: "2026-Feb",
      subject: "Physics, Chemistry, Math MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 12,
      name: "Sojib",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2026-Feb",
      subject: "Physics, Chemistry, Math MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    
    {
      id: 14,
      name: "Sathi",
      batchTime: "7 am to 8 am",
      class_name: "দশম ",
      imgLink: "https://i.ibb.co/ng54MVX/sathi.jpg",
      joinYear: "2024 [অষ্টম]",
      subject: "Physics, Chemistry, Math-MCQ",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 15,
      name: "Moriyom",
      batchTime: "7 am to 8 am",
      class_name: "দশম ",
      imgLink: "",
      joinYear: "2025 [নবম]",
      subject: "Physics, Chemistry, Math-MCQ",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 16,
      name: "Mim",
      batchTime: "7 am to 8 am",
      class_name: "দশম ",
      imgLink: "",
      joinYear: "2026-July",
      subject: "Physics, Chemistry, Math-MCQ",
      institutionName: "নাকাইহাট গার্লস স্কুল এন্ড কলেজ।",
    },
    {
      id: 12,
      name: "Siam",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2026-July",
      subject: "Physics, Chemistry, Math MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 12,
      name: "Nihad",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2026-July",
      subject: "Physics, Chemistry, Math MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 12,
      name: "Kawsar",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2026-July",
      subject: "Physics, Chemistry, Math MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 12,
      name: "Mizan",
      batchTime: "8 am to 9 am",
      class_name: "দশম",
      imgLink: "",
      joinYear: "2026-July",
      subject: "Physics, Chemistry, Math MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    
  ],
  Nine: [
    {
      id: 1,
      name: "Jahid",
      batchTime: "9 am to 10 am",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/hFDLdbwc/jahid-Hasan-At9.jpg",
      joinYear: "২০২৬-ফেব্রুয়ারী",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },

    {
      id: 2,
      name: "Noyon Kumar",
      batchTime: "9 am to 10 am",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/XkMdGnQM/noyon-Kumar.jpg",
      joinYear: "২০২৬-ফেব্রুয়ারী",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 3,
      name: "Abdul Ahad",
      batchTime: "9 am to 10 am",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/Y4sYqgt6/ab-ahad.jpg",
      joinYear: "২০২৬-মে",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 4,
      name: "Monowar",
      batchTime: "9 am to 10 am",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/27Sd51WF/monowar.jpg",
      joinYear: "২০২৬-ফেব্রুয়ারী",
      subject: "পদার্থ,রসায়ন,গণিত -MCQ",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 5,
      name: "Tasin [Lamiya]",
      batchTime: "4:45 pm to 5:45 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৫-এপ্রিল- অষ্টম শ্রেণি",
      subject: "গণিত, বিজ্ঞান",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 6,
      name: "Bulbul",
      batchTime: "5:45 pm to 6:45 pm",
      class_name: "নবম",
      imgLink: "https://i.ibb.co.com/99b41xQP/bulbul9.jpg",
      joinYear: "২০২৬-মে",
      subject: "গণিত ও বিজ্ঞান ।",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 7,
      name: "Golap",
      batchTime: "5:45 pm to 6:45 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "গণিত ও বিজ্ঞান ।",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 8,
      name: "Umar Faruk",
      batchTime: "9 am to 10 am",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 9,
      name: "Jannatul Mawa",
      batchTime: "4:45 pm to 5:45 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "গণিত ",
      institutionName: "নাকাইহাট গার্লস স্কুল  এন্ড কলেজ।",
    },
    {
      id: 10,
      name: "Mukta",
      batchTime: "9 am to 10 am",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "নাকাইহাট গার্লস স্কুল  এন্ড কলেজ।",
    },
    {
      id: 11,
      name: "Aysha",
      batchTime: "9 am to 10 am",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "নাকাইহাট গার্লস স্কুল  এন্ড কলেজ।",
    },
    {
      id: 13,
      name: "Nirob",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    {
      id: 14,
      name: "Umme Hani",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    {
      id: 15,
      name: "Umar Akmol",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    {
      id: 16,
      name: "Jannti",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    {
      id: 17,
      name: "Tafhimul",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: " ",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    {
      id: 18,
      name: "Robbani",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: "",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    {
      id: 19,
      name: "Rifat",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: "",
      joinYear: "২০২৬-জুন",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    {
      id: 19,
      name: "Toufik",
      batchTime: "3:30 pm to 4:30 pm",
      class_name: "নবম",
      imgLink: "",
      joinYear: "২০২৬-February",
      subject: "পদার্থ, রসায়ন & গণিত- MCQ",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)।",
    },
    
    
  ],
  Eight: [
    {
      id: 1,
      name: "Md Ibrahim",
      batchTime: "5:45 pm to 6:45 pm",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/xxW1txy/ibrahim-8-2.jpg",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 2,
      name: "Rifa",
      batchTime: "4:45 pm to 5:45 pm",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/gZd8Vg9H/rifa.jpg",
      joinYear: "2026 -শ্রেনি-৮ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 3,
      name: "Sagorika",
      batchTime: "4:45 pm to 5:45 pm",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/v4sYNf6x/sagorika.jpg",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    
    {
      id: 5,
      name: "Mim",
      batchTime: "4:45 pm to 5:45 pm",
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/svFGRBNc/mim.jpg",
      joinYear: "2026 -শ্রেনি-৮ম", 
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 6,
      name: "Likhon",
      batchTime: "5:45 pm to 6:45 pm",     
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/Cp4pYgTQ/Likhon8.jpg",
      joinYear: "2026 -শ্রেনি-৮ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 7,
      name: "Rifat",
      batchTime: "5:45 pm to 6:45 pm",     
      class_name: "অষ্টম",
      imgLink: "https://i.ibb.co.com/SDchLbFT/rifat8.jpg",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
    {
      id: 8,
      name: "Sourov",
      batchTime: "5:45 pm to 6:45 pm",     
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "আলোর মেলা শিশু নিকেতন।",
    },
    {
      id: 9,
      name: "Ahisk",
      batchTime: "5:45 pm to 6:45 pm",     
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2026-July -শ্রেনি-৮ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 10,
      name: "Emon",
      batchTime: "5:45 pm to 6:45 pm",     
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2026-July -শ্রেনি-৮ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 11,
      name: "Bonna",
      batchTime: "4:45 pm to 5:45 pm",
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    },
     {
      id: 12,
      name: "Biplob",
      batchTime: "5:45 pm to 6:45 pm",     
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "আলোর মেলা শিশু নিকেতন।",
    },
    
  ],
};




export const PreviousStudentsData = {
  ssc25: [
    {
      id: 1,
      name: "Soikot",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/6c7mnWYv/soikot-26.jpg",
      joinYear: "2025",
      subject: "Physics and Chemistry",
      institutionName: "নাকাইহাট দ্বি-মুখী মাধ্যমিক বিদ্যালয়।",
    },
    {
      id: 13,
      name: "Miraz",
      batchTime: "7 am to 8 am",
      batch: "দশম ",
      imgLink: "https://i.ibb.co.com/nCVYVGz/miraz.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "আলোর মেলা শিশু নিকেতন।",
    },
    {
      id: 4,
      name: "Ayesha",
      batchTime: "4:45 pm to 5:45 pm",
      class_name: "অষ্টম",
      imgLink: "",
      joinYear: "2026-জুন ",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "আলোর মেলা শিশু নিকেতন।",
    },
    {
      id: 2,
      name: "Alif",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/7sgpnpG/alif.jpg",
      joinYear: "2025",
      subject: "Physics and Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    {
      id: 3,
      name: "Mehedi",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/rfXKx9xx/mehedi-26.jpg",
      joinYear: "2025",
      subject: "Physics and Chemistry",
      institutionName: "মেহেদীবাগ উচ্চ বিদ্যালয়।",
    },
    // { id: 4, name: "Shihab", batch:"SSC-2026 [২০২৫-২০২৬]",imgLink: "" ,joinYear:'',subject:"Physics and Chemistry",institutionName:"সাকসেস মডেল স্কুল (পুরাতন)"},
    {
      id: 5,
      name: "Maruf",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/1YtMMyvW/maruf-26.jpg",
      joinYear: "",
      subject: "Physics and Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },
    // { id: 6, name: "Riad", batch:"SSC-2026 [২০২৫-২০২৬]",imgLink: "" ,joinYear:'',subject:"Physics and Chemistry",institutionName:"সাকসেস মডেল স্কুল (পুরাতন)"},
    {
      id: 7,
      name: "Mahin",
      batch: "SSC-2026 [২০২৫-২০২৬]",
      imgLink: "https://i.ibb.co.com/39CV0SLt/mahin-26.jpg",
      joinYear: "",
      subject: "Physics and Chemistry",
      institutionName: "সাকসেস মডেল স্কুল (পুরাতন)",
    },

    {
      id: 2,
      name: "Lamiya",
      batch: "নবম [২০২৫]",
      imgLink: "https://i.ibb.co.com/WGXGHLQ/lamiya-2.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "নুরুল হক স্কুল এন্ড কলেজ।",
    },
    {
      id: 3,
      name: "Rukaiya",
      batch: " নবম [২০২৫]",
      imgLink: "https://i.ibb.co/syMd0zG/rukaiya.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
    {
      id: 7,
      name: "Munna",
      batch: "নবম [২০২৫]",
      imgLink: "https://i.ibb.co.com/ymj9sGtM/munna-nine.jpg",
      joinYear: "2024",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },
     
    {
      id: 5,
      name: "Mohon",
      batch: "অষ্টম [২০২৪] ",
      imgLink: "https://i.ibb.co.com/9vB0Xqr/mohon2.png",
      joinYear: "2023",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },


    // ///////
    
    {
      id: 3,
      name: "Sadiya",
      batch: "দশম [২০২৬]",
      imgLink: "https://i.ibb.co.com/Cv0kzMd/Capture.png",
      joinYear: "",
      subject: "Physics",
      institutionName: "সাকসেস মডেল স্কুল (নতুন)",
    },





     {
      id: 1,
      name: "Luba",
      batch: "HSC ICT [2024]",
      imgLink: "https://i.ibb.co.com/ZzHXCY0/luba.jpg",
      joinYear: "2024",
      subject: "ICT",
      institutionName: "Nakai hat collage",
    },
     {
      id: 1,
      name: "Shithi",
      batch: "HSC ICT [2024]",
      imgLink: "https://i.ibb.co.com/ChN22g9/shithi-2.png",
      joinYear: "2024",
      subject: "ICT",
      institutionName: "Nakai hat collage",
    },

    {
      id: 3,
      name: "Borhan",
      batch: "HSC ICT [2024]",
      imgLink: "https://i.ibb.co.com/KDhg3v7/borhan-2.png",
      joinYear: "",
      subject: "",
      institutionName: "SKS School and Collage",
    },
    
    {
      id: 4,
      name: "Bonna",
      batch: "অষ্টম",
      imgLink: "",
      joinYear: "2025 -শ্রেনি-৭ম",
      subject: "গণিত, বিজ্ঞান,গ্রামার",
      institutionName: "পশ্চিম পগইল দাখিল মাদ্রাসা",
    }
  ],
  
};
